# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 03:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(db_column='pk_conta', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome_conta', max_length=100)),
                ('cor_layout', models.CharField(choices=[('primary', 'Azul'), ('sucess', 'Verde'), ('warning', 'Laranja'), ('danger', 'Vermelho'), ('pink', 'Rosa'), ('dark', 'Preto'), ('purple', 'Roxo')], db_column='cor_layout_conta', max_length=10)),
                ('tipo', models.IntegerField(choices=[('', 'Selecione...'), (1, 'Conta Corrente'), (2, 'Conta Poupança'), (3, 'Dinheiro na Carteira'), (4, 'Investimento'), (5, 'Outros Tipos')], db_column='tipo_conta')),
                ('saldo', models.DecimalField(db_column='saldo_conta', decimal_places=2, max_digits=15)),
                ('data_inicio', models.DateField(db_column='data_inicio_conta')),
                ('status_ativa', models.BooleanField(db_column='status_ativa_conta', default=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True, db_column='data_modificacao_conta', null=True)),
                ('usuario', models.ForeignKey(db_column='fk_user_conta', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_conta',
            },
        ),
    ]
