# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 00:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(db_column='pk_tag', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='nome_tag', max_length=100)),
                ('data_modificacao', models.DateTimeField(auto_now=True, db_column='data_modificacao_tag', null=True)),
                ('usuario', models.ForeignKey(db_column='fk_user_tag', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_tag',
            },
        ),
        migrations.AlterField(
            model_name='conta',
            name='cor_layout',
            field=models.CharField(choices=[('primary', 'Azul'), ('sucess', 'Verde'), ('warning', 'Laranja'), ('danger', 'Vermelho'), ('pink', 'Rosa'), ('default', 'Cinza'), ('purple', 'Roxo'), ('info', 'info')], db_column='cor_layout_conta', max_length=10),
        ),
    ]
